import Head from 'next/head'
import Header from '../components/Header'
import Login from '../components/Login'
import { getSession } from "next-auth/react"
import Sidebar from '../components/Sidebar'


export default function Home({ session }) {

  if (!session) {
    return (<Login />)
  } 
  return (
    <div>
      
      <Head>
        <title>Facebook 2.0</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      {/* Header */}
      <Header />
      <main>
        {/* Sidebar */}
        <Sidebar />
        {/* Feed */}
        {/* Widgets */}
      </main>
    </div>
  )
}

export async function getServerSideProps(context) {
  const session = await getSession(context);

  return {
    props: {
      session
    },
  }
}